import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Echo Chamber',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
   <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className,
      "bg-sky-100 dark:bg-slate-800 ")
      }>
        {/* Именно в строке выше мы делаем свои кастомные светлую и тёмную темы */}
        <ThemeProvider
        attribute='class'
        defaultTheme='dark'
        enableSystem = {false}
        storageKey='EchoChamber-theme'
        >
        {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>

  )
}
